
server:
  port: 8730
  #client（客户端）向server（服务器）注册服务的配置
  #instance.appname:指明注册中的名字
  #service-url.defaultZone:配置注册中心地址
  eureka:
    client:
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka/
  servlet:
    context-path: /commons
  #应用名字
spring:
  application:
      name: person
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: wzz1997
      driver-class-name:  com.mysql.cj.jdbc.Driver
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/mapper/*.xml


